services:
  db:
    image: postgres:15-alpine
    container_name: database
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: dev_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: server
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: dev_user
      DB_PASSWORD: dev_password
      DB_NAME: dev_db
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

  frontend:
    build: ../frontend
    container_name: frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    volumes:
      - ../frontend:/app
      - /app/node_modules

volumes:
  pgdata: